name: Build

on:
  push:
    branches:
      - main
  schedule: # Run everyday
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: articulate/http-to-https:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=articulate/http-to-https:latest
          cache-to: type=inline
